apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-secret
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/91458399268/secrets/sql-pass/versions/1"
        fileName: "MYSQL_PASSWORD"

